"""WAL-TAT: transactional, causally ranked ternary conversion."""

from .campaign import (
    accepted_weight_counts,
    atomic_write_json,
    coverage_proportional_nll_gate,
    validate_checkpoint_deletion_target,
    worst_ratio,
)
from .controller import (
    AdaptiveTransactionSizer,
    GateDecision,
    RatioGate,
    TransactionController,
    TransactionSizeDecision,
)
from .compensation import (
    linked_down_group_mask,
    linked_gqa_output_group_mask,
    linked_gqa_query_group_mask,
    linked_output_group_mask,
    structured_channel_candidate_mask,
    structured_down_candidate_mask,
)
from .evaluation import LossMetrics, evaluate_causal_lm
from .speech_evaluation import (
    PairedWERBootstrap,
    SpeechLossMetrics,
    WordErrorCounts,
    corpus_word_error_counts,
    evaluate_speech_seq2seq_loss,
    paired_bootstrap_wer,
    word_error_counts,
)
from .binary import (
    ProxyBinaryLinear,
    ProxyBinaryMatrix,
    pack_binary_codes,
    q1_g128_physical_bpw,
    soft_binary_proxy,
    unpack_binary_codes,
    weighted_binary_project,
)
from .binary_packing import (
    PackedB1Matrix,
    pack_binary_matrix,
    read_packed_binary_matrix,
    unpack_binary_matrix,
    write_packed_binary_matrix,
)
from .fixed_lowbit import (
    FixedGroupwiseLinear,
    FixedPartialGroupwiseLinear,
    ProjectionStatistics,
    install_fixed_checkpoint,
    install_trainable_lowbit_checkpoint,
    install_packed_lowbit_manifest,
    install_packed_t3_manifest,
    install_fixed_projection,
    project_linear_module,
)
from .speech_data import SpeechExample, decode_audio_payload, iter_hf_speech_examples
from .moments import CausalMomentCollector, InputSecondMomentCollector
from .mixed import (
    FixedMixedQ2Q4Linear,
    MixedArtifactInstallResult,
    install_mixed_q2_q4_artifact,
    valid_group_weight_count,
)
from .codebook import (
    FixedColumnCodebookLinear,
    FixedMixedColumnCodebookLinear,
    MixedColumnCodebookProjection,
    column_codebook_payload_bits,
    column_codebook_physical_bpw,
    column_outlier_density,
    mixed_column_codebook_payload_bits,
    mixed_column_codebook_project,
    reconstruct_column_codebook,
    weighted_column_codebook_project,
)
from .packing import (
    PackedQ2Matrix,
    pack_bool_mask,
    pack_partial_matrix,
    pack_ternary_codes,
    read_packed_matrix,
    true_artifact_bpw,
    unpack_bool_mask,
    unpack_partial_matrix,
    unpack_ternary_codes,
    write_packed_matrix,
)
from .quantization import (
    hard_codes_scales,
    hestia_quantize,
    initial_group_scales,
    q4_g128_physical_bpw,
    q8_g128_physical_bpw,
    q2_g128_physical_bpw,
    transaction_schedule,
    weighted_symmetric_odd_level_project,
    weighted_symmetric_nz4_project,
    weighted_symmetric_q4_project,
    weighted_symmetric_q8_project,
)
from .rate_distortion import (
    FormatOption,
    RateDistortionAllocation,
    allocate_rate_distortion,
    groupwise_payload_bits,
)
from .proxy import (
    ProxyTernaryLinear,
    ProxyTernaryMatrix,
    soft_ternary_proxy,
    soft_ternary_proxy_derivative,
)
from .discrete_repair import (
    apply_top_groupwise_ternary_moves,
    apply_top_groupwise_ternary_moves_across_matrices,
    consensus_ternary_move_scores,
    ternary_newton_proposals,
)
from .orchestration import (
    active_campaign_workers,
    common_campaign_frontier,
    load_campaign_state,
    sha256_file,
    synchronize_campaign_frontiers,
)
from .scoring import (
    activation_fisher_group_damage,
    diagonal_ternary_search,
    exact_diagonal_ternary_project,
    group_weight_mse,
    select_group_mask,
    sensitivity_decile_mask,
)
from .transaction import (
    AtomicTernaryTransaction,
    TransactionalTernaryLinear,
    TransactionalTernaryMatrix,
)
from .transforms import (
    FixedTernaryLinear,
    TransformedProxyTernaryLinear,
    blockwise_randomized_hadamard,
    inverse_blockwise_randomized_hadamard,
    normalized_hadamard,
    rademacher_signs,
)
from .uncertainty import paired_block_bootstrap_nll
from .wal import HashChainWAL, WALIntegrityError, WALRecord
from .whisper import (
    WhisperFamilySpec,
    WhisperLinearSpec,
    WhisperTransactionGroup,
    freeze_except_transactional,
    get_module,
    install_transactional_group,
    set_module,
)
from .whisper_equalization import value_output_channel_equalization

__all__ = [
    "FixedTernaryLinear",
    "FixedGroupwiseLinear",
    "FixedPartialGroupwiseLinear",
    "TransformedProxyTernaryLinear",
    "blockwise_randomized_hadamard",
    "inverse_blockwise_randomized_hadamard",
    "normalized_hadamard",
    "rademacher_signs",
    "CausalMomentCollector",
    "InputSecondMomentCollector",
    "FixedMixedQ2Q4Linear",
    "FixedColumnCodebookLinear",
    "FixedMixedColumnCodebookLinear",
    "MixedColumnCodebookProjection",
    "MixedArtifactInstallResult",
    "FormatOption",
    "RateDistortionAllocation",
    "AdaptiveTransactionSizer",
    "AtomicTernaryTransaction",
    "GateDecision",
    "HashChainWAL",
    "LossMetrics",
    "PairedWERBootstrap",
    "ProxyBinaryLinear",
    "ProxyBinaryMatrix",
    "ProjectionStatistics",
    "PackedQ2Matrix",
    "PackedB1Matrix",
    "RatioGate",
    "SpeechLossMetrics",
    "SpeechExample",
    "TransactionController",
    "TransactionSizeDecision",
    "TransactionalTernaryLinear",
    "TransactionalTernaryMatrix",
    "WALIntegrityError",
    "WALRecord",
    "WhisperFamilySpec",
    "WhisperLinearSpec",
    "WhisperTransactionGroup",
    "WordErrorCounts",
    "activation_fisher_group_damage",
    "accepted_weight_counts",
    "atomic_write_json",
    "coverage_proportional_nll_gate",
    "diagonal_ternary_search",
    "exact_diagonal_ternary_project",
    "evaluate_causal_lm",
    "evaluate_speech_seq2seq_loss",
    "decode_audio_payload",
    "corpus_word_error_counts",
    "freeze_except_transactional",
    "get_module",
    "group_weight_mse",
    "hard_codes_scales",
    "hestia_quantize",
    "initial_group_scales",
    "install_mixed_q2_q4_artifact",
    "column_codebook_payload_bits",
    "column_codebook_physical_bpw",
    "column_outlier_density",
    "mixed_column_codebook_payload_bits",
    "mixed_column_codebook_project",
    "reconstruct_column_codebook",
    "weighted_column_codebook_project",
    "allocate_rate_distortion",
    "groupwise_payload_bits",
    "install_fixed_projection",
    "install_fixed_checkpoint",
    "install_trainable_lowbit_checkpoint",
    "install_packed_lowbit_manifest",
    "install_packed_t3_manifest",
    "linked_down_group_mask",
    "linked_gqa_output_group_mask",
    "linked_gqa_query_group_mask",
    "linked_output_group_mask",
    "iter_hf_speech_examples",
    "q2_g128_physical_bpw",
    "q1_g128_physical_bpw",
    "q4_g128_physical_bpw",
    "q8_g128_physical_bpw",
    "weighted_symmetric_odd_level_project",
    "weighted_symmetric_nz4_project",
    "weighted_symmetric_q4_project",
    "weighted_symmetric_q8_project",
    "paired_block_bootstrap_nll",
    "pack_bool_mask",
    "pack_binary_codes",
    "pack_binary_matrix",
    "pack_partial_matrix",
    "pack_ternary_codes",
    "ProxyTernaryLinear",
    "ProxyTernaryMatrix",
    "soft_ternary_proxy",
    "soft_ternary_proxy_derivative",
    "apply_top_groupwise_ternary_moves",
    "apply_top_groupwise_ternary_moves_across_matrices",
    "consensus_ternary_move_scores",
    "ternary_newton_proposals",
    "soft_binary_proxy",
    "active_campaign_workers",
    "common_campaign_frontier",
    "load_campaign_state",
    "sha256_file",
    "synchronize_campaign_frontiers",
    "select_group_mask",
    "sensitivity_decile_mask",
    "structured_channel_candidate_mask",
    "structured_down_candidate_mask",
    "transaction_schedule",
    "true_artifact_bpw",
    "paired_bootstrap_wer",
    "read_packed_matrix",
    "read_packed_binary_matrix",
    "unpack_bool_mask",
    "unpack_partial_matrix",
    "unpack_binary_codes",
    "unpack_binary_matrix",
    "unpack_ternary_codes",
    "validate_checkpoint_deletion_target",
    "valid_group_weight_count",
    "write_packed_matrix",
    "write_packed_binary_matrix",
    "weighted_binary_project",
    "project_linear_module",
    "word_error_counts",
    "install_transactional_group",
    "set_module",
    "value_output_channel_equalization",
    "worst_ratio",
]
